version: '3.1'

services:
  node:
    build:
      dockerfile: Dockerfile
      context: .
    
    command: npm run immutable-start

    ports:
      - "3000:3000"
    volumes:
      - .:/opt/app
    environment:
      - NODE_ENV=production
